# Staytus environment configuration. Staytus uses
# unix environment variables to provide its configuration.
# If your hosting environment does not support setting this
# easily, you can add them to config/environment.yml and
# they will be loaded when the application starts.

# The theme to use
STAYTUS_THEME: 'default'

# If enabled, the application will allow any username/password
# combination to login to the admin area.
STAYTUS_DEMO: '0'
